version:  0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - favicon.ico
    - Biplab_Mazumder_CV.pdf
    - styles/main.css
    - images/*
